apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-test-deployment
  labels:
    app: devops-test-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-test-deployment
  template:
    metadata:
      labels:
        app: devops-test-deployment
    spec:
      containers:
        - name: devops-test-deployment
          image: dewnisubasinghe/dewni-assignment1
          ports:
            - containerPort: 8080
